### ISSUE TITLE
Cannot redirect stderr/stdout to file?

### ISSUE THREAD

**Issue by joefiorini** [colinkeenan/silentcast#10]
I'm having issues getting silentcast to work on my Arch installation running Awesome wm. I was going to open an issue with the output I'm getting, but redirecting stderr doesn't seem to output errors to a file. When I run: `silentcast 2>&1 > silentcast.txt` and then `cat silentcast.txt` I don't see the error output I saw when running the program. Worth noting that the error output is going to the terminal, so obviously the redirection isn't working.

**Comment by colinkeenan** [comment]
The reason redirect is not working is because Silentcast uses ffmpeg and from my testing just now, it is ffmpeg that is not allowing redirect. If you don't use `2>&1`, you'll have something in silentcast.txt, but just not the error, which you are apparently getting from ffmpeg. I will investigate how to redirect ffmpeg error output to a file.

**Comment by colinkeenan** [comment]
From [here](http://stackoverflow.com/questions/2066076/how-do-i-enable-ffmpeg-logging-and-where-can-i-find-the-ffmpeg-log-file), it looks like ffmpeg does sometimes allow redirect, but I think it doesn't when capturing the screen because it needs to let you know to press 'q' to stop it. From another answer on that link, you can use `-report` to generate a verbose report of what happens though. In order to use that, you would need to either edit `genffcom`, or the file it generates `silentcast\ffcom`. You can edit `slientcast\ffcom` while the "Get Ready .... Click OK when ready to start recording....." popup dialogue is displayed. I think that is the best way to do this. You can then grep the log for errors if you want. It will generate a file like `silentcast/ffmpeg-20150123-083319.log`.

**Comment by colinkeenan** [comment]
Instead of editing `silentcast/ffcom`, you could also do as I did and, from within the silentcast directory where `ffcom` was generated, `cat ffcom`, highlight and middle-click the `ffcom` command without the `&...` stuff at the end, and put `-report` at the end.
