### ISSUE TITLE
unable to install on Ubuntu 14.04

### ISSUE THREAD

**Issue by ghost** [colinkeenan/silentcast#37]
Sorry, this may be elementary... not much up on workings with Ubuntu, but I have tried both through the software center and command line to install and I get the following through command line:

$ sudo add-apt-repository ppa:sethj/silentcast

$ sudo apt-get update

$ sudo apt-get install silentcast

Upon execution of the last command, I get the following messages:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 silentcast : Depends: ffmpeg but it is not installable
E: Unable to correct problems, you have held broken packages.

If I try from the Synaptic Manager, I get the following:

silentcast:
 Depends: ffmpeg  but it is not installable
 Depends: yad but it is not going to be installed
 Depends: xdotool but it is not going to be installed
 Depends: imagemagick
 Depends: wmctrl

I would like to try the program and would appreciate any advice as to how to proceed.  

Thanks!

**Comment by Seth-Johnson** [comment]
What version of Ubuntu are you running (or elementary)?

**Comment by colinkeenan** [comment]
If you are using 16.04 or 16.10, maybe you need to do this:

`sudo add-apt-repository universe`

I don't use Ubuntu, but some searching found that command for adding the repository that should have ffmpeg.

**Comment by colinkeenan** [comment]
Also, I'm pretty sure that by the end of January, I'll have a completely different UI for silentcast worked out because I'm learning Gtk3 by re-writing Silentcast in it. I'm having it start with a full-screen translucent window with a green rectangle drawn around the active window. That rectangle can be moved or resized. I've got that part working although there are still some issues with detecting the active window geometry (was much easier using bash tools). Overall, it will be much easier to use when I come out with this Gtk version.

**Comment by billdee5501** [comment]
Seth, I'm running Ubuntu 14.04 LTS.  Colin, thanks for the suggestion, but when I tried it, I got this message: 'universe' distribution component is already enabled for all sources.

**Comment by colinkeenan** [comment]
Searching for how to install in 14.04 gave this as the top result: 

http://www.faqforge.com/linux/how-to-install-ffmpeg-on-ubuntu-14-04/

It explains that ffmpeg was removed from 14.04 then re-added in 15.04. It provides a tutorial for installing ffmpeg. Seth used to include ffmpeg in the silentcast package, but removed it since it's available in recent versions of Ubuntu.

**Comment by Seth-Johnson** [comment]
Ugh. I thought we had made it past the those times. My bad.  Let me see what I can do.

**Comment by billdee5501** [comment]
Thanks, Colin, that seemed to do it!  Installed ffmpeg first, then followed the three commands above for install.  By the way, how is the program working?  It looks like it first makes an MKV file, then a GIF from that if I'm not mistaken.  Are the GIFs uncompressed?

**Comment by billdee5501** [comment]
Thanks, Colin.  The MKV is indeed uncompressed, which is exactly what I have been seeking because I am going to use the resulting data in another video and I needed ideal quality to begin with.  I find too many issues trying to import compressed videos into other programs to make a master video.  It's also nice to have the image option too.  One area I'm having trouble with is area to be screen captured.   On the second page menu, I chose "WxH", but I didn't realize at first that I am then supposed to replace "W" and "H" with whatever video size I am seeking (at least that is my impression).  So I input, say, 400x400 and click and then I get the cross, but I don't see any boundaries as to what I am about to record.  If I then click the cross, the dialogue pops up about "manual resize and position" and it says to "move the next active window to the area to be recorded, and resize manually if desired"  but I don't see any box appearing to resize.  I click ok to start recording and I am getting the MKV, but for the entire screen, not just one area, so any help here would be welcome.  Thanks again!

**Comment by colinkeenan** [comment]
It is because of these UI issues that I am rewriting this in Gtk3 with a UI based entirely on a resizable and movable rectangle. For your purposes, it sounds like you should choose "Transparent Window" as the "Area to be recorded". You can then choose a pre-set size for the transparent window, or enter a size like 400x400, or manually resize the transparent window by dragging as usual. If you want to just record an entire window, you can leave it on "Entirety of a Window" instead of choosing "Transparent Window", but enter the size, like 400x400 and it will resize the window you want to record before recording begins.
