### ISSUE TITLE
Icon doesn't appear on notifications area

### ISSUE THREAD

**Issue by Cvetomird91** [colinkeenan/silentcast#44]
Hello,

Thank you for your effort and the software. 

I would like to report an issue that occured on CentOS 7 x64 with GNOME shell version 3.14.4.

I hadn't used CentOS in a while and this particular version of GNOME shell. I'll observer the issue and check if my settings aren't appropriate for this to work and will update this issue if I have more info.

![anim](https://cloud.githubusercontent.com/assets/5771574/23069882/c9f35f4c-f531-11e6-96b0-674210ca0592.gif)

**Comment by colinkeenan** [comment]
@Seth-Johnson noticed the same problem in Unity on Ubuntu and fixed it before packaging the latest release for Ubuntu. The fix is simple. I didn't want to do another release before finishing my whole new UI based on Gtk3 which I was making fast progress on in December 2016, but I've been busy with other things in my life and haven't worked on Silentcast in 2017 yet., I will do another release that fixes this issue later today.

**Comment by colinkeenan** [comment]
See if v2.6 solves it.
