### ISSUE TITLE
i3 instructions are not working for me

### ISSUE THREAD

**Issue by jwhendy** [colinkeenan/silentcast#54]
I'm on ubuntu xenial, installed manually (`make`, then `sudo install`), and copied the `i3` workaround into my `~/.config/i3/config` at the end. I have no other bindings to `$mod+Shift+s`, `$mod+z`, or `$mod+x`.

I start silentcast from the commandline, get the big green box, and as soon as I do `$mod+Shift+s` it triggers the pop up that it's going to convert the gif and asks if I want to drop frames.

I had success skipping that and just doing `$mod+z` and it recorded.

Subsequently I found that trying to use F2 to change the numbers/positions triggered the recording, and that as soon as I was done entering those values it triggered the mkv -> gif process as well, and I got a screencast of changing the values.

In addition, the process even triggers a bizarre wallpaper change from what I set via `i3` with `feh` to the canned Ubuntu unity wallpaper! I _think_ it's the auto-opening of a file browser after perhaps?

Any thoughts on how I can troubleshoot this?

**Comment by colinkeenan** [comment]
I will try to take a look at this by Friday. Thanks for reporting the issue.

**Comment by colinkeenan** [comment]
I have started to work on this by installing Ubuntu 16.04 LTS in VirtualBox and setting everything up to be able to clone and run Silentcast in i3 (with compton and dependencies). I did not have all the issues that you had, but the last one definitely happened (weird desktop, which pretty much blocked anything else happening so I shutdown the virtual machine).

I'm sure that you are right that the auto-opening of the file browser to show the finished files is what causes this major issue. I will work on it over the weekend.

Everything else just following my notes in the ~/.config/i3/config worked. I didn't use F1 F2 F3 yet. Here's what worked for me. I opened a couple of windows (firefox and guake), ran silentcast in guake (green box), pressed $mod+Shift+s (it went transparent but the green box didn't show until I used the mouse to move it around), moved the green box to firefox instead of the terminal, $mod+z and it recorded, $mod+x and it stopped recording asking if I wanted to prune, I didn't prune and continued, it probably made anim.gif, but that's when I got the desktop covering everything and blocking me, so I shut down the machine.

**Comment by jwhendy** [comment]
I'm pretty new to `i3` and set things up according to bits and pieces I found around the web. I don't know if any workspace, dimming inactive, borders, or anything else would muck with the silentcast workaround, but thought I could post my configs for [i3](https://gist.github.com/jwhendy/9ce7ede18ca515ee5f65a3fa5d2a6308) and [compton](https://gist.github.com/jwhendy/4fa4dcc2511ff2ec3c7860fa38af0b61) if that's helpful?

**Comment by jwhendy** [comment]
So I just tried again and am not getting the weird background change. I did find that I can skip the `Shift+$mod+s` step entirely and it seems to work! I right click + dragged to set the box, did `$mod+z` to start it, and `$mod+x` to stop. 

One oddity which I *think* might be known to `i3` users is when I'm setting the box, I see my wallpaper, not the windows behind it. [This report](https://github.com/DaveDavenport/rofi/issues/338) suggests that "this is how i3 handles full screen windows."

F2 still appears to trigger the start of the screencast. I started `silentcast`, pressed F2, set the size, and then did `$mod+z`, but it immediately jumped to making the gif steps, which shows me setting the size. Click+drag is working though, so for now I'm a much happier camper at least knowing it works!

**Comment by colinkeenan** [comment]
I have been very busy this weekend and won't be able to work on this for a couple more days, but you should not skip Shift+$mod+s because that's what takes care of the issue you mentioned where you don't see the windows but instead see the desktop.

**Comment by jwhendy** [comment]
No problem, and understood. I will putz with that, but currently `Shift+$mod+s` triggers the post-processing dialog immediately. Maybe I'll ditch my custom i3 and compton configs just to start trying to rule things out. Thanks for the help and no rush at all!

**Comment by jwhendy** [comment]
Returning to this as silentcast is awesome and it just isn't cooperating for one reason or another. Not sure what would be most helpful for you?

- [i3 config](https://pastebin.com/Ajg37rDw)
- [compton config](https://pastebin.com/7fm7xawY)
- [.Xresources](https://pastebin.com/LdeGmW3Q) (pretty sure this is what Ubuntu 16.04 users; on arch it's .Xdefaults). I technically have both as I wrestled with Ubuntu; if you suspect that's an issue, let me know. Does the terminal matter?

I continue to get the same behavior. Run `silentcast` from `rxvt-unicode` press `Shift+$mod+s` and immediately get the `anim.gif` popup and a fraction of a second resultant movie.

Any pointers of where to look further would be appreciated!

```
$ i3 --version
i3 version 4.15.0.1-168-ga25ab05 (2018-05-20, branch "gaps-next") © 2009 Michael Stapelberg and contributors
```

**Comment by colinkeenan** [comment]
I will try to look at this within a week.

**Comment by colinkeenan** [comment]
I am going to put a little time into this finally. I honestly don't have time to make serious coding changes though.

Just starting to look at your i3 config and noticed you didn't change the screen size from what I had in the instructions. Did you follow this part of the instructions:

      # After copy and pasting this, make sure to change the display size at the end
      # of the first definition ($enable_floating_fullscreen) to match your display size

Is your screen size 1920 x 1080?

**Comment by jwhendy** [comment]
Dangit. I remember checking that and meant to add it to the post, but forgot. Indeed it is:
```
$ xrandr
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 16384 x 16384
DP-0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 193mm
   1920x1080     60.01*+  40.01 
```

**Comment by jwhendy** [comment]
Hmmm. I just tried again for the heck of it on arch and things work as expected. I'll try again from ubuntu shortly, but I don't think it's ever worked for me on either, so this seems promising!

**Comment by colinkeenan** [comment]
I didn't realize it wasn't working for you on Arch. I thought the problem was just Ubuntu 16.04 LTS. Let me know what happens on Ubuntu.

**Comment by colinkeenan** [comment]
I just tried it again in VirtualBox with Ubuntu 16.04 LTS, and it works perfectly. I fixed the only problem I was having last time I tried. That was the issue with the desktop wallpaper popping up at the end and covering everything when silentcast opened the file manager. It turns out, this is an issue with i3m and the nautilus file manager, not silentcast. Running the following command in a terminal permanently fixes the issue:

    gsettings set org.gnome.desktop.background show-desktop-icons false

**Comment by colinkeenan** [comment]
If it also works for you (after running that command), please "close and comment".

**Comment by jwhendy** [comment]
Arch is my main distro, but weirdly maybe I never have tried it? It wasn't installed when I went to try today, but this is a newer system as of earlier this year. Who knows.

Tidbit for reference on arch:
```
$ gsettings get org.gnome.desktop.background show-desktop-icons
false
```
So, it will be interesting to see what it is on ubuntu.

**Comment by jwhendy** [comment]
While that setting was `true` on ubuntu, I get the same behavior after setting it to `false`. `$mod+Shift+s` immediately triggers the popup for `anim.temp` and ffmpeg running where I started `silentcast` from the terminal.

Any chance to try this from a live install? Like could there be an oddity when working with virtual hardware vs. a real system? I can look into doing the same. Any possible differences in our i3 or other setups? *Any* other program that could conflict with the workspace switching or other functionality?

**Comment by colinkeenan** [comment]
I don't think this has anything to do with your setup. Maybe running on hardware would make a difference, but if it did, it would mean I have to change the code again, which I don't have time for now. It's definitely possible that different distros require different code. There's already some code that might be specific to arch linux having to do with how the return keypress is processed.

However, since it works in a VM, it might be somehow specific to your hardware. So, either I would have to mess with the code again, which I don't have time for anytime in the foreseeable future, or it's specific to your hardware which I don't have access to.

I'm going to close this, but would still like to find out what happens when you try this in a VM running Ubuntu 16.04 LTS.

**Comment by jwhendy** [comment]
Hardware seems unlikely given arch and ubuntu are installed to the same laptop (I triple boot). I think it's some oddity in the setup somewhere, though both share the same i3 config (symlinked). Maybe some version issue on arch (always up to date) vs. ubuntu (lags a lot)? Dunno, but appreciate your persistence in at least taking a look. No idea from me.

**Comment by colinkeenan** [comment]
If it had something to do with the versions of software, it would've shown up for me in the VM. I installed Ubuntu 16.04 and did not experience the issue you have. I hope you will try it in a VM and report back.
